name: First Workflow

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Shell Command
        run: echo "Hello World"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Node Version
        run: |
          npm install
          npm run test